Need to access the items of the additional arguments otherwise you get:
Traceback (most recent call last):
  File "./sublime_plugin.py", line 350, in run_
  File "./phpunit.py", line 864, in run
  File "./phpunit.py", line 167, in run
ValueError: too many values to unpack